# Generated by Django 5.0.7 on 2024-07-19 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания запроса')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('weather_main', models.CharField(max_length=30, verbose_name='Группа погодных параметров')),
                ('weather_description', models.CharField(max_length=250, verbose_name='Состояние погоды в группе')),
                ('temperature', models.FloatField(verbose_name='Температура, градусы Цельсия')),
                ('temperature_feels_like', models.FloatField(verbose_name='Человеческое восприятие погоды, градусы Цельсия')),
                ('sea_pressure', models.PositiveSmallIntegerField(verbose_name='Атмосферное давление на уровне моря, гПа')),
                ('ground_pressure', models.PositiveSmallIntegerField(verbose_name='Атмосферное давление на уровне земли, гПа')),
                ('humidity', models.PositiveSmallIntegerField(verbose_name='Влажность, %')),
                ('visibility', models.PositiveSmallIntegerField(verbose_name='Видимость, метр')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра, метр/сек')),
                ('wind_deg', models.PositiveSmallIntegerField(verbose_name='Направление ветра, градусы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос прогноза погоды',
                'verbose_name_plural': 'Запросы прогноза погоды',
                'ordering': ('-created',),
            },
        ),
    ]
